# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michem/repos/OTTO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michem/repos/OTTO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michem/repos/OTTO/CMakeFiles /home/michem/repos/OTTO/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michem/repos/OTTO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OTTO

# Build rule for target.
OTTO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OTTO
.PHONY : OTTO

# fast build rule for target.
OTTO/fast:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/build
.PHONY : OTTO/fast

src/bitboard.o: src/bitboard.cpp.o

.PHONY : src/bitboard.o

# target to build an object file
src/bitboard.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/bitboard.cpp.o
.PHONY : src/bitboard.cpp.o

src/bitboard.i: src/bitboard.cpp.i

.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s

.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/evaluation.o: src/evaluation.cpp.o

.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/evaluation.cpp.o
.PHONY : src/evaluation.cpp.o

src/evaluation.i: src/evaluation.cpp.i

.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/evaluation.cpp.i
.PHONY : src/evaluation.cpp.i

src/evaluation.s: src/evaluation.cpp.s

.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/evaluation.cpp.s
.PHONY : src/evaluation.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/movegen.o: src/movegen.cpp.o

.PHONY : src/movegen.o

# target to build an object file
src/movegen.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/movegen.cpp.o
.PHONY : src/movegen.cpp.o

src/movegen.i: src/movegen.cpp.i

.PHONY : src/movegen.i

# target to preprocess a source file
src/movegen.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/movegen.cpp.i
.PHONY : src/movegen.cpp.i

src/movegen.s: src/movegen.cpp.s

.PHONY : src/movegen.s

# target to generate assembly for a file
src/movegen.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/movegen.cpp.s
.PHONY : src/movegen.cpp.s

src/mt64.o: src/mt64.cpp.o

.PHONY : src/mt64.o

# target to build an object file
src/mt64.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/mt64.cpp.o
.PHONY : src/mt64.cpp.o

src/mt64.i: src/mt64.cpp.i

.PHONY : src/mt64.i

# target to preprocess a source file
src/mt64.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/mt64.cpp.i
.PHONY : src/mt64.cpp.i

src/mt64.s: src/mt64.cpp.s

.PHONY : src/mt64.s

# target to generate assembly for a file
src/mt64.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/mt64.cpp.s
.PHONY : src/mt64.cpp.s

src/openbook.o: src/openbook.cpp.o

.PHONY : src/openbook.o

# target to build an object file
src/openbook.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/openbook.cpp.o
.PHONY : src/openbook.cpp.o

src/openbook.i: src/openbook.cpp.i

.PHONY : src/openbook.i

# target to preprocess a source file
src/openbook.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/openbook.cpp.i
.PHONY : src/openbook.cpp.i

src/openbook.s: src/openbook.cpp.s

.PHONY : src/openbook.s

# target to generate assembly for a file
src/openbook.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/openbook.cpp.s
.PHONY : src/openbook.cpp.s

src/search.o: src/search.cpp.o

.PHONY : src/search.o

# target to build an object file
src/search.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/search.cpp.o
.PHONY : src/search.cpp.o

src/search.i: src/search.cpp.i

.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s

.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/zobristhash.o: src/zobristhash.cpp.o

.PHONY : src/zobristhash.o

# target to build an object file
src/zobristhash.cpp.o:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/zobristhash.cpp.o
.PHONY : src/zobristhash.cpp.o

src/zobristhash.i: src/zobristhash.cpp.i

.PHONY : src/zobristhash.i

# target to preprocess a source file
src/zobristhash.cpp.i:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/zobristhash.cpp.i
.PHONY : src/zobristhash.cpp.i

src/zobristhash.s: src/zobristhash.cpp.s

.PHONY : src/zobristhash.s

# target to generate assembly for a file
src/zobristhash.cpp.s:
	$(MAKE) -f CMakeFiles/OTTO.dir/build.make CMakeFiles/OTTO.dir/src/zobristhash.cpp.s
.PHONY : src/zobristhash.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OTTO"
	@echo "... src/bitboard.o"
	@echo "... src/bitboard.i"
	@echo "... src/bitboard.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/movegen.o"
	@echo "... src/movegen.i"
	@echo "... src/movegen.s"
	@echo "... src/mt64.o"
	@echo "... src/mt64.i"
	@echo "... src/mt64.s"
	@echo "... src/openbook.o"
	@echo "... src/openbook.i"
	@echo "... src/openbook.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/zobristhash.o"
	@echo "... src/zobristhash.i"
	@echo "... src/zobristhash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

